### ISSUE TITLE
Peer review - Repository

### ISSUE THREAD

**Issue by victorboucher** [lisaoude/artist-guesser#1]
Your repo looks very clean, you already had the project live on heroku and have updated everything according to your concept. You have described the API and dependencies that you use very well.
These are the only things missing from your repo:
- The data life cycle
- Real-time events explained

Your readme is looking good (as expected), good job on already being up to date. This will save you a lot of time in the coming weeks 🚀

**Comment by lisaoude** [comment]
Thanks for the feedback! 😄 

---

## To Do:
- [ ] Data lifecycle diagram
- [ ] Explain real-time events

**Comment by lisaoude** [comment]
This issue has been added to my issue summary. Thanks again!
