### ISSUE TITLE
Peer review - Data lifecycle diagram

### ISSUE THREAD

**Issue by victorboucher** [lisaoude/artist-guesser#10]
Good job on actually making this diagram, like I have said before, I can learn a lot from you regarding documentation etc...
The diagram is really clear, I understand it completely and it shows how your data moves around between the client and server. I don't really have anything to add. I am not sure if it was a requirement for this course, but I see that you do not store any data, you might want to add this if there is time. And maybe any get/post requests that you handle in your project.

**Comment by lisaoude** [comment]
This issue has been added to my issue summary. Thanks again!
