### ISSUE TITLE
Peer review - Code

### ISSUE THREAD

**Issue by victorboucher** [lisaoude/artist-guesser#11]
Your code and structure is looking very clean, here are some things you could improve on:
- You call this function every single time a new user connects and then send the new data to all users. This would change the image every single time a new user connects. You would just want to run the function once and keep the data the same for all users. https://github.com/lisaoude/artist-guesser/blob/b662a5eaa8954ccd87d1c04c4f5f29574f0a21d4/app.js#L35
- You can remove this line since you don't use the node-fetch dependency in your app.js https://github.com/lisaoude/artist-guesser/blob/b662a5eaa8954ccd87d1c04c4f5f29574f0a21d4/app.js#L12
- If you only have a single route in your project, I don't really see the use of having a separate router. This might be 'best practice' but if you are keeping it to a single route this will add extra complexity to your project structure for no reason, since you could just add 3 lines of code to your app.js file for the same effect. (if you are planning on adding more routes tho, just ignore this)
Everything is looking great, you are missing a big part of the functionality of your application tho. So I would recommend to try getting everything to work asap. I am really curious about the finished product, good luck! 🚀

**Comment by lisaoude** [comment]
This issue has been added to my issue summary. Thanks again!
