### ISSUE TITLE
Peer review: Data Cycle

### ISSUE THREAD

**Issue by Lottetekulve** [lisaoude/artist-guesser#13]
- Je data cycle ziet er goed uit, hier en daar mist nog wat maar dat hoorde je al van Wouter.
- Wel zijn er veel dingen in je live cycle die je nog niet hebt, maak het jezelf niet te moeilijk die laatste paar dagen. Focus op goed of fout antwoord en een 'volgende' mogelijkheid. 
- Laat dan misschien start button tot het einde als je echt tijd over hebt, dan moet je alleen even kijken hoe je dat wil doen met als een gebruiker joint, dat het niet reload/ of dat je zegt, 'wacht met spelen tot alle gebruikers aanwezig zijn'. Dit is even een kleine oplossing voor als je niet meer aan die start knop toekomt :)

**Comment by lisaoude** [comment]
This issue has been added to my issue summary. Thanks again!
