### ISSUE TITLE
Peer review - Code App.js ⚙️

### ISSUE THREAD

**Issue by sanneduinkerx** [lisaoude/artist-guesser#14]
- in app.js on line 13 is a random `;` 😁
- The comments above every section makes it more clear and easier to read! 
- In the socket.io you do the same thing as me so i can't really give more feedback on that 😊
- But Victor said to me that the data gets updated every time a user connects and if you were to put that data in a var outside of io.on that it wouldn't update every time a user connects. I have to change that myself too.

**Comment by lisaoude** [comment]
This issue has been added to my issue summary. Thanks again!
