### ISSUE TITLE
Peer review - Concept

### ISSUE THREAD

**Issue by victorboucher** [lisaoude/artist-guesser#2]
The concept is very clear, simple but powerful. The description of the concept is not that large, but I don't think it has to be any more comprehensive, it is already very clear and does not have to take a lot of words to explain.
The chat in the live version already works. You can fill in your name, and chat with other users. But the rest of the functionality is not yet available in your live version (which is understandable). The chat works great tho, so good job on that!
I would recommend just starting on the feature of your app where the guessing of the artist works and gives feedback to the users. I did about the same thing with my concept, so you might want to take a look at my backend code for some inspiration [=>](https://github.com/BVictorB/real-time-web-2021/blob/master/server/index.js)
Good luck!

**Comment by lisaoude** [comment]
Thanks for the feedback! 😄
