### ISSUE TITLE
Peer Review 🤓 - Repo 

### ISSUE THREAD

**Issue by sanneduinkerx** [lisaoude/artist-guesser#4]
## Overall Repo 📋
- Readme is as good as complete!
- Only thing missing is Data Life Cycle 🔄
- Link demo and description is included 👍🏻
- Maybe later you can a screenshot from your web app. 📸
- It looks really cool with the emojis to spice it up and a table of contents to navigate quickly, also the wishlist you made is useful to go back to when you don't know what to do anymore. 

## Concept 💻
- User interface from concept sketch looks very good! 
- I understand the concept -> artist guesser as it says in the name 😋

## Real Time events  🛠
- In the peer review doc ([here](https://github.com/cmda-minor-web/real-time-web-2021/blob/main/course/peer-review.md#steps)) it says to also put used events from the websocket in the readme. I myself didn't have that either, but its good to put events you use in your documentation.

## To Do 📚
- [ ] Later add a data life cycle with data you are gonna send to client or server and get from the API. (you can look at mine to have an example ☺️)
- [ ] A screenshot from your web app added by app description
- [ ] Describe used real time events

**Comment by lisaoude** [comment]
Thanks for the feedback! 😄

**Comment by lisaoude** [comment]
This issue has been added to my issue summary. Thanks again!
