### ISSUE TITLE
Peer review - API info

### ISSUE THREAD

**Issue by victorboucher** [lisaoude/artist-guesser#6]
You already have quite a clear explanation of the API that you use. But here are some things that you could add:
- Explanation how to get an API key from the source
- Fetch example with the data that you get as response from the API
- Maybe a bit of your code where you show how you use this API

I don't think this is all necessary to add, but it would be a nice addition. And since you are the readme.md queen, this is the least that we can expect of you.

**Comment by lisaoude** [comment]
Thanks for the feedback! 😄 

---

## To Do:
- [ ] Describe what I did with the API
- [x] Explain how to get the API key
- [x] Add an example of how to fetch data from the API (connect)
- [x] Add example of how API is used

**Comment by lisaoude** [comment]
This issue has been added to my issue summary. Thanks again!
